In [1]:
import pandas as pd

In [6]:
data = pd.read_csv('challenge.csv')

In [11]:
len(data['dst_ip'].unique())

5497

In [10]:
len(data['src_ip'].unique())

5497

In [12]:
data.describe()

           src_port      dst_port       payload
count  2.445669e+07  2.445669e+07  2.445669e+07
mean   2.278892e+03  2.257839e+03  2.444282e+02
std    1.211225e+03  1.213766e+03  9.403660e+01
min    5.300000e+01  5.300000e+01  6.800000e+01
25%    1.709000e+03  1.699000e+03  1.610000e+02
50%    1.993000e+03  1.993000e+03  2.540000e+02
75%    3.389000e+03  3.389000e+03  3.260000e+02
max    4.500000e+03  4.500000e+03  4.500000e+02

In [13]:
data

,timestamp,src_ip,dst_ip,src_port,dst_port,protocol,payload
0,2020-06-21 00:00:02.892702,120.18.164.170,120.18.53.84,2459,53,UDP,218
1,2020-06-21 00:00:03.771702,120.18.53.84,120.18.164.170,53,2459,UDP,285
2,2020-06-21 00:00:03.989702,120.18.164.170,148.26.83.117,2495,443,TCP,142
3,2020-06-21 00:00:04.547702,148.26.83.117,120.18.164.170,443,2495,TCP,130
4,2020-06-21 00:00:05.170953,120.18.187.161,120.18.63.42,3487,1993,TCP,69
...,...,...,...,...,...,...,...
24456688,2020-06-25 23:01:16.406536,251.139.203.226,120.18.142.45,1993,2386,UDP,385
24456689,2020-06-25 23:01:17.554536,120.18.142.45,251.139.203.226,2386,1993,UDP,220
24456690,2020-06-25 23:01:18.500536,251.139.203.226,120.18.142.45,1993,2386,UDP,350
24456691,2020-06-25 23:01:18.579536,120.18.142.45,251.139.203.226,2386,1993,UDP,317
24456692,2020-06-25 23:01:19.563536,251.139.203.226,120.18.142.45,1993,2386,UDP,383

### EDA

In [31]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24456693 entries, 0 to 24456692
Data columns (total 7 columns):
 #   Column     Dtype
---  ------     -----
 0   timestamp  object
 1   src_ip     object
 2   dst_ip     object
 3   src_port   int64
 4   dst_port   int64
 5   protocol   object
 6   payload    int64
dtypes: int64(3), object(4)
memory usage: 1.3+ GB

In [37]:
data_aggragated = data.groupby(['src_ip', 'dst_ip']).agg({'payload': ['sum','count'] , 'src_port': 'count', 'dst_port': 'count'})

In [39]:
data_as_pairs = data_aggragated.reset_index()

In [43]:
data_as_pairs

               src_ip          dst_ip payload       src_port dst_port
                                          sum count    count    count
0       1.108.196.149    120.18.12.38      75     1        1        1
1       1.108.196.149  120.18.120.241     705     2        2        2
2       1.108.196.149    120.18.138.6     135     1        1        1
3       1.108.196.149   120.18.147.29     759     3        3        3
4       1.108.196.149    120.18.147.8     236     1        1        1
...               ...             ...     ...   ...      ...      ...
439216  99.97.103.225    120.18.81.81     273     1        1        1
439217  99.97.103.225   120.18.84.124     873     4        4        4
439218  99.97.103.225   120.18.84.125     697     3        3        3
439219  99.97.103.225    120.18.88.16     516     3        3        3
439220  99.97.103.225   120.18.98.125    1002     4        4        4

[439221 rows x 6 columns]

In [45]:
data_as_pairs = data_as_pairs.sort_values(by=('payload', 'sum') , ascending=False)

                src_ip          dst_ip   payload         src_port dst_port
                                             sum   count    count    count
424191         8.8.8.8    120.18.53.84  35014529  155423   155423   155423
225018    120.18.53.84         8.8.8.8  24795472  155370   155370   155370
174913  120.18.236.161  120.18.214.239   4211852   13341    13341    13341
149428  120.18.214.239  120.18.236.161   4037967   12666    12666    12666
72220    120.18.154.54  120.18.214.239   3710123   11660    11660    11660
...                ...             ...       ...     ...      ...      ...
313854  167.149.135.58   120.18.216.16        68       1        1        1
282789   130.161.79.57  120.18.137.128        68       1        1        1
370828   240.138.6.133  120.18.204.125        68       1        1        1
261885    120.18.88.93  157.10.138.118        68       1        1        1
268355    120.18.92.19  189.217.47.147        68       1        1        1

[439221 rows x 6 columns]

In [46]:
data[data['src_ip'] == '8.8.8.8']

,timestamp,src_ip,dst_ip,src_port,dst_port,protocol,payload
1898,2020-06-21 00:30:54.247736,8.8.8.8,120.18.53.84,53,1837,UDP,196
1900,2020-06-21 00:30:54.908736,8.8.8.8,120.18.53.84,53,1837,UDP,196
2000,2020-06-21 00:32:31.594100,8.8.8.8,120.18.53.84,53,3424,UDP,164
2430,2020-06-21 00:40:16.525777,8.8.8.8,120.18.53.84,53,4108,UDP,249
2981,2020-06-21 00:50:18.875126,8.8.8.8,120.18.53.84,53,2828,UDP,237
...,...,...,...,...,...,...,...
24455360,2020-06-25 22:59:30.587177,8.8.8.8,120.18.53.84,53,1718,UDP,265
24455468,2020-06-25 22:59:34.390288,8.8.8.8,120.18.53.84,53,2503,UDP,220
24455515,2020-06-25 22:59:35.916205,8.8.8.8,120.18.53.84,53,2276,UDP,220
24456052,2020-06-25 22:59:54.627029,8.8.8.8,120.18.53.84,53,1171,UDP,176
24456171,2020-06-25 22:59:59.339587,8.8.8.8,120.18.53.84,53,1356,UDP,232

In [49]:
data[data['src_ip'] == '8.8.8.8']['dst_ip'].unique()

array(['120.18.53.84'], dtype=object)

In [53]:
data[data['src_ip'] == '120.18.53.84']['dst_ip'].unique()

array(['120.18.164.170', '120.18.213.107', '120.18.192.121',
       '120.18.206.150', '120.18.120.241', '120.18.118.50',
       '120.18.104.36', '120.18.216.242', '120.18.48.222',
       '120.18.18.124', '120.18.45.124', '120.18.26.88', '120.18.57.96',
       '120.18.162.115', '120.18.143.87', '120.18.182.116',
       '120.18.110.15', '120.18.66.102', '120.18.23.222', '120.18.71.37',
       '120.18.88.93', '120.18.159.247', '120.18.178.138',
       '120.18.143.73', '120.18.218.147', '120.18.132.135',
       '120.18.173.154', '8.8.8.8', '120.18.168.250', '120.18.157.13',
       '120.18.103.76', '120.18.205.198', '120.18.96.34',
       '120.18.171.175', '120.18.55.138', '120.18.9.187', '120.18.207.47',
       '120.18.195.179', '120.18.251.35', '120.18.27.78', '120.18.235.29',
       '120.18.202.14', '120.18.156.202', '120.18.188.182',
       '120.18.67.141', '120.18.49.122', '120.18.22.239',
       '120.18.184.225', '120.18.70.11', '120.18.39.116', '120.18.9.252',
       '120.18.43.27', '120.18.187.183', '120.18.14.179', '120.18.2.221',
       '120.18.114.123', '120.18.187.233', '120.18.187.161',
       '120.18.218.225', '120.18.112.246', '120.18.32.75',
       '120.18.217.238', '120.18.178.2', '120.18.131.73',
       '120.18.207.248', '120.18.106.17', '120.18.173.175',
       '120.18.106.180', '120.18.64.244', '120.18.217.176',
       '120.18.90.239', '120.18.54.24', '120.18.51.9', '120.18.231.142',
       '120.18.206.230', '120.18.187.234', '120.18.34.156',
       '120.18.128.229', '120.18.138.6', '120.18.161.137',
       '120.18.254.217', '120.18.60.53', '120.18.191.193',
       '120.18.199.149', '120.18.83.125', '120.18.50.229', '120.18.74.17',
       '120.18.246.188', '120.18.224.228', '120.18.231.65',
       '120.18.71.176', '120.18.235.102', '120.18.157.66',
       '120.18.139.59', '120.18.189.21', '120.18.49.202', '120.18.252.47',
       '120.18.99.247', '120.18.59.72', '120.18.31.162', '120.18.191.171',
       '120.18.218.213', '120.18.69.128', '120.18.247.96',
       '120.18.179.95', '120.18.92.114', '120.18.248.164',
       '120.18.125.201', '120.18.201.228', '120.18.244.68',
       '120.18.165.123', '120.18.60.25', '120.18.92.60', '120.18.153.200',
       '120.18.195.23', '120.18.152.175', '120.18.19.244',
       '120.18.228.102', '120.18.114.73', '120.18.236.252',
       '120.18.51.101', '120.18.231.49', '120.18.147.93', '120.18.178.60',
       '120.18.61.207', '120.18.81.48', '120.18.173.71', '120.18.45.68',
       '120.18.240.90', '120.18.179.1', '120.18.87.33', '120.18.15.225',
       '120.18.228.126', '120.18.210.168', '120.18.57.61',
       '120.18.180.110', '120.18.5.253', '120.18.188.217',
       '120.18.160.223', '120.18.236.18', '120.18.31.34', '120.18.82.191',
       '120.18.132.228', '120.18.215.38', '120.18.18.133',
       '120.18.53.227', '120.18.243.88', '120.18.248.110',
       '120.18.151.162', '120.18.10.95', '120.18.129.235',
       '120.18.98.125', '120.18.3.216', '120.18.26.229', '120.18.217.161',
       '120.18.27.110', '120.18.113.65', '120.18.163.20', '120.18.93.29',
       '120.18.165.36', '120.18.17.46', '120.18.130.196',
       '120.18.201.129', '120.18.73.221', '120.18.43.42', '120.18.227.9',
       '120.18.27.32', '120.18.92.185', '120.18.111.75', '120.18.160.99',
       '120.18.39.9', '120.18.249.99', '120.18.162.99', '120.18.119.92',
       '120.18.87.128', '120.18.105.98', '120.18.156.46',
       '120.18.248.144', '120.18.172.227', '120.18.238.3',
       '120.18.186.212', '120.18.23.27', '120.18.114.56', '120.18.5.52',
       '120.18.203.67', '120.18.216.187', '120.18.15.208',
       '120.18.72.186', '120.18.39.44', '120.18.36.13', '120.18.12.38',
       '120.18.149.15', '120.18.181.252', '120.18.189.206',
       '120.18.155.63', '120.18.67.143', '120.18.123.76', '120.18.173.18',
       '120.18.243.147', '120.18.224.248', '120.18.179.89',
       '120.18.6.146', '120.18.92.235', '120.18.126.60', '120.18.142.45',
       '120.18.154.54', '120.18.1.187', '120.18.229.20', '120.18.14.123',
       '120.18.140.165', '120.18.146.190', '120.18.118.79',
       '120.18.124.167', '120.18.247.202', '120.18.219.23',
       '120.18.81.81', '120.18.125.99', '120.18.182.230', '120.18.93.210',
       '120.18.88.125', '120.18.53.181', '120.18.162.200',
       '120.18.84.125', '120.18.49.14', '120.18.171.92', '120.18.158.121',
       '120.18.75.62', '120.18.19.39', '120.18.7.139', '120.18.109.224',
       '120.18.176.122', '120.18.188.152', '120.18.64.65',
       '120.18.225.33', '120.18.108.218', '120.18.108.184',
       '120.18.210.69', '120.18.102.219', '120.18.85.182',
       '120.18.172.179', '120.18.24.144', '120.18.212.32',
       '120.18.201.198', '120.18.205.249', '120.18.85.57',
       '120.18.37.202', '120.18.214.198', '120.18.52.160',
       '120.18.131.88', '120.18.156.8', '120.18.236.161', '120.18.85.233',
       '120.18.56.143', '120.18.66.69', '120.18.241.10', '120.18.154.145',
       '120.18.77.170', '120.18.109.2', '120.18.185.238', '120.18.155.96',
       '120.18.88.5', '120.18.236.227', '120.18.227.15', '120.18.84.124',
       '120.18.125.31', '120.18.240.47', '120.18.138.212',
       '120.18.35.113', '120.18.236.117', '120.18.9.177',
       '120.18.155.114', '120.18.152.102', '120.18.66.8',
       '120.18.137.253', '120.18.17.184', '120.18.219.104',
       '120.18.193.158', '120.18.55.234', '120.18.32.157',
       '120.18.80.227', '120.18.76.250', '120.18.43.251',
       '120.18.152.107', '120.18.167.142', '120.18.108.45',
       '120.18.133.234', '120.18.254.81', '120.18.104.5', '120.18.234.3',
       '120.18.120.204', '120.18.228.187', '120.18.48.217',
       '120.18.164.147', '120.18.212.63', '120.18.104.107',
       '120.18.132.126', '120.18.112.182', '120.18.213.196',
       '120.18.148.67', '120.18.247.54', '120.18.194.178', '120.18.40.67',
       '120.18.114.187', '120.18.123.198', '120.18.184.70',
       '120.18.188.68', '120.18.28.59', '120.18.12.170', '120.18.194.17',
       '120.18.123.205', '120.18.79.44', '120.18.106.56', '120.18.20.145',
       '120.18.173.82', '120.18.80.22', '120.18.254.57', '120.18.49.20',
       '120.18.4.79', '120.18.143.130', '120.18.64.93', '120.18.124.158',
       '120.18.163.64', '120.18.94.103', '120.18.2.84', '120.18.139.96',
       '120.18.9.15', '120.18.240.104', '120.18.138.14', '120.18.253.76',
       '120.18.88.16', '120.18.245.11', '120.18.63.77', '120.18.61.169',
       '120.18.31.136', '120.18.66.204', '120.18.139.7', '120.18.46.66',
       '120.18.216.201', '120.18.210.112', '120.18.187.108',
       '120.18.147.8', '120.18.30.196', '120.18.204.125',
       '120.18.157.239', '120.18.229.69', '120.18.115.245',
       '120.18.79.252', '120.18.102.62', '120.18.168.163',
       '120.18.143.194', '120.18.170.253', '120.18.243.189',
       '120.18.84.30', '120.18.218.124', '120.18.209.157', '120.18.43.39',
       '120.18.241.209', '120.18.168.3', '120.18.141.208',
       '120.18.121.193', '120.18.196.70', '120.18.75.5', '120.18.70.215',
       '120.18.193.229', '120.18.231.141', '120.18.160.75',
       '120.18.147.29', '120.18.95.181', '120.18.226.93', '120.18.17.201',
       '120.18.92.192', '120.18.191.87', '120.18.177.118',
       '120.18.185.101', '120.18.134.115', '120.18.47.79',
       '120.18.190.26', '120.18.53.5', '120.18.86.166', '120.18.87.244',
       '120.18.34.121', '120.18.2.124', '120.18.216.16', '120.18.92.245',
       '120.18.90.185', '120.18.73.203', '120.18.79.242',
       '120.18.192.127', '120.18.123.47', '120.18.240.8', '120.18.23.132',
       '120.18.34.238', '120.18.114.211', '120.18.156.193', '120.18.16.2',
       '120.18.74.251', '120.18.239.152', '120.18.77.208', '120.18.92.19',
       '120.18.53.150', '120.18.131.160', '120.18.251.233',
       '120.18.29.209', '120.18.49.253', '120.18.31.223', '120.18.147.65',
       '120.18.203.12', '120.18.216.159', '120.18.37.7', '120.18.45.222',
       '120.18.114.248', '120.18.234.124', '120.18.208.163',
       '120.18.171.176', '120.18.221.235', '120.18.252.116',
       '120.18.229.240', '120.18.88.56', '120.18.102.141',
       '120.18.129.50', '120.18.158.160', '120.18.136.32',
       '120.18.240.140', '120.18.237.1', '120.18.169.125',
       '120.18.229.154', '120.18.72.222', '120.18.149.185',
       '120.18.63.42', '120.18.17.156', '120.18.3.194', '120.18.107.52',
       '120.18.36.143', '120.18.97.164', '120.18.210.80', '120.18.184.43',
       '120.18.224.201', '120.18.67.46', '120.18.196.188',
       '120.18.203.56', '120.18.192.61', '120.18.169.3', '120.18.160.94',
       '120.18.201.232', '120.18.83.231', '120.18.231.9',
       '120.18.168.231', '120.18.202.49', '120.18.114.190',
       '120.18.152.36', '120.18.84.55', '120.18.192.228', '120.18.67.176',
       '120.18.157.134', '120.18.178.205', '120.18.100.24',
       '120.18.129.117', '120.18.192.245', '120.18.241.224',
       '120.18.10.62', '120.18.152.58', '120.18.138.79', '120.18.241.89',
       '120.18.54.9', '120.18.16.159', '120.18.102.12', '120.18.132.113',
       '120.18.150.156', '120.18.75.225', '120.18.64.41', '120.18.187.76',
       '120.18.133.83', '120.18.252.16', '120.18.182.168',
       '120.18.112.47', '120.18.8.29', '120.18.155.26', '120.18.187.112',
       '120.18.112.28', '120.18.161.10', '120.18.143.167',
       '120.18.215.19', '120.18.58.80', '120.18.225.211', '120.18.64.46',
       '120.18.74.118', '120.18.12.176', '120.18.15.122', '120.18.226.69',
       '120.18.55.80', '120.18.58.165', '120.18.167.184', '120.18.170.22',
       '120.18.137.128', '120.18.149.224', '120.18.157.23'], dtype=object)